#ifndef GUACAPLUS_VERSION_HPP
#define GUACAPLUS_VERSION_HPP

#define GUACAPLUS_VERSION "1.0.0"

#define GUACAPLUS_MAJOR_VERSION 1
#define GUACAPLUS_MINOR_VERSION 0
#define GUACAPLUS_PATCH_VERSION 0

#endif  // GUACAPLUS_VERSION_HPP

